import { useEffect, useState } from "react";
import { plannerApi } from "../api/plannerApi";

function normalizeSettings(s) {
  const safe = {
    startTime: s?.startTime || "08:00",
    dailyMaxHours: Number(s?.dailyMaxHours || 2),
    breakEveryMinutes: Number(s?.breakEveryMinutes || 50),
    breakDurationMinutes: Number(s?.breakDurationMinutes || 10),
  };

  if (safe.dailyMaxHours <= 0) safe.dailyMaxHours = 2;
  if (safe.breakEveryMinutes < 15) safe.breakEveryMinutes = 50;
  if (safe.breakDurationMinutes < 5) safe.breakDurationMinutes = 10;

  return safe;
}

export default function Schedule({ settings, schedule, setSchedule, missed, setMissed }) {
  const [busy, setBusy] = useState(false);

  useEffect(() => {
    (async () => {
      try {
        const data = await plannerApi.getMissed();
        setMissed(Array.isArray(data) ? data : []);
      } catch {
        setMissed([]);
      }
    })();
  }, [setMissed]);

  async function generate() {
    setBusy(true);
    try {
      const payload = normalizeSettings(settings);
      const data = await plannerApi.generateSchedule(payload);

      if (Array.isArray(data) && data.length > 0) {
        setSchedule(data);
      } else {
        // do not wipe existing schedule if backend returned empty unexpectedly
        alert("No schedule generated. Check: subjects added + settings values.");
      }
    } catch (e) {
      alert(`Schedule generation failed: ${e.message}`);
      // keep previous schedule
    } finally {
      setBusy(false);
    }
  }

  async function markMissed(item) {
    if (!item?.subjectId) return;

    try {
      await plannerApi.markMissed(item.subjectId);
      const data = await plannerApi.getMissed();
      setMissed(Array.isArray(data) ? data : []);
    } catch {
      // ignore
    }
  }

  return (
    <div className="space-y-5">
      <div className="rounded-3xl border bg-white p-5 shadow-sm">
        <div className="flex flex-col gap-3 md:flex-row md:items-center md:justify-between">
          <div>
            <div className="text-sm font-semibold text-slate-900">Daily Schedule</div>
            <div className="mt-1 text-sm text-slate-500">
              Generated by backend using Circular Linked List → MaxHeap (array).
            </div>
          </div>

          <button
            onClick={generate}
            disabled={busy}
            className="rounded-2xl bg-blue-600 px-5 py-3 text-sm font-semibold text-white shadow-sm hover:bg-blue-700 disabled:opacity-60"
          >
            {busy ? "Generating..." : "Generate Schedule"}
          </button>
        </div>
      </div>

      <div className="rounded-3xl border bg-white p-6 shadow-sm">
        <div className="flex items-center justify-between">
          <div>
            <div className="text-base font-semibold text-slate-900">Today Plan</div>
            <div className="mt-1 text-sm text-slate-500">Study + break blocks</div>
          </div>
          <div className="text-sm font-semibold text-slate-900">{(schedule || []).length} items</div>
        </div>

        <div className="mt-5 overflow-x-auto">
          <table className="w-full text-sm">
            <thead className="text-left text-slate-500">
              <tr>
                <th className="py-3">Type</th>
                <th className="py-3">Start</th>
                <th className="py-3">Duration</th>
                <th className="py-3">Subject</th>
                <th className="py-3">Priority</th>
                <th className="py-3"></th>
              </tr>
            </thead>
            <tbody>
              {(schedule || []).map((s, idx) => (
                <tr key={idx} className="border-t">
                  <td className="py-3 font-semibold text-slate-900">{s.type}</td>
                  <td className="py-3 text-slate-700">{s.startTime}</td>
                  <td className="py-3 text-slate-700">{s.durationMinutes} min</td>
                  <td className="py-3 text-slate-700">{s.type === "study" ? s.subjectName : "-"}</td>
                  <td className="py-3 text-slate-700">{s.type === "study" ? `${s.priority}/5` : "-"}</td>
                  <td className="py-3">
                    {s.type === "study" ? (
                      <button
                        onClick={() => markMissed(s)}
                        className="rounded-2xl border px-4 py-2 text-sm font-semibold text-slate-700 hover:bg-slate-50"
                      >
                        Mark Missed
                      </button>
                    ) : null}
                  </td>
                </tr>
              ))}

              {(schedule || []).length === 0 ? (
                <tr>
                  <td className="py-6 text-slate-500" colSpan={6}>
                    No schedule yet.
                  </td>
                </tr>
              ) : null}
            </tbody>
          </table>
        </div>

        <div className="mt-5 rounded-3xl border bg-slate-50 p-4">
          <div className="text-sm font-semibold text-slate-900">Missed sessions</div>
          <div className="mt-1 text-sm text-slate-600">
            {missed?.length ? `${missed.length} missed item(s) recorded in backend.` : "No missed sessions recorded."}
          </div>
        </div>
      </div>
    </div>
  );
}