spring.application.name=Planner-ms
server.port=8080
logging.level.org.springframework.web=INFO
logging.level.com.pdsa=DEBUG
spring.jackson.serialization.indent_output=true
spring.jackson.time-zone=Asia/Colombo
server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-stacktrace=never
